### ISSUE TITLE
I got a problem when i use react-card-carousel

### ISSUE THREAD

**Issue by komardev** [TomorrowIdeas/react-card-carousel#5]
i got this message, Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method, so what should i do in my component now ?

**Comment by strawbee** [comment]
Thanks for letting me know about the issue. I haven't gotten this on my end - could you post your code so that I can try to track it down?

**Comment by komardev** [comment]
> 
> 
> Thanks for letting me know about the issue. I haven't gotten this on my end - could you post your code so that I can try to track it down?
![image](https://user-images.githubusercontent.com/52956253/68724716-d8731f00-05ee-11ea-8207-863c91fc1282.png)

**Comment by komardev** [comment]
and in my componentDidMount im using wowJs

**Comment by strawbee** [comment]
The code you posted seems correct and I'm not getting any issues when I replicate it. It seems like a problem elsewhere in your component, not with react-card-carousel. The warning refers to your componentWillUnmount method - try removing code from there, or it may be a problem with a different dependency. I'm going to close this issue.

**Comment by strawbee** [comment]
Hi! I looked into this further and there was an issue with the card carousel. :) It should be fixed in version 1.1.3. Thanks!

**Comment by komardev** [comment]
> 
> 
> Hi! I looked into this further and there was an issue with the card carousel. :) It should be fixed in version 1.1.3. Thanks!

Thanks !
