### ISSUE TITLE
Pausing the carousel

### ISSUE THREAD

**Issue by LeonardoSSev** [TomorrowIdeas/react-card-carousel#6]
Is there a way that I can pause the carousel manually? I mean, after an implemented event, the carousel stops at the current card and then it comes back after another event?

**Comment by strawbee** [comment]
Currently there isn't a way to do that. I messed with it for a while but ran into some issues with event bubbling/capturing and the async nature of setState, so will have to put this on the back burner until I have more time to tackle it. Will keep it in mind for future releases and update you if so. Thanks!
